CREATE TABLE IF NOT EXISTS public.categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name CHARACTER VARYING(255),
    CONSTRAINT pk_categories PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_categories_name ON public.categories (name);

CREATE TABLE IF NOT EXISTS public.compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pinned BOOLEAN                                 NOT NULL,
    title  CHARACTER VARYING(255)                  NOT NULL,
    CONSTRAINT pk_compilations PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_compilations_title ON public.compilations (title);

CREATE TABLE IF NOT EXISTS public.location
(
    lat REAL NOT NULL,
    lon REAL NOT NULL,
    PRIMARY KEY (lat, lon)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email CHARACTER VARYING(255)                  NOT NULL,
    name  CHARACTER VARYING(255)                  NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_users_email ON public.users (email);

CREATE TABLE IF NOT EXISTS public.events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    annotation         CHARACTER VARYING(2000)                 NOT NULL,
    confirmed_requests INTEGER                                 NOT NULL,
    created_on         TIMESTAMP WITHOUT TIME ZONE,
    description        CHARACTER VARYING(7000),
    event_date         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    paid               BOOLEAN                                 NOT NULL,
    participant_limit  INTEGER,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    request_moderation BOOLEAN,
    state              CHARACTER VARYING(255),
    title              CHARACTER VARYING(120),
    views              BIGINT,
    category_id        BIGINT                                  NOT NULL,
    user_id            BIGINT                                  NOT NULL,
    location_lat       REAL,
    location_lon       REAL,
    CONSTRAINT pk_events PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES public.users (id) ON UPDATE NO ACTION ON DELETE NO ACTION,
    FOREIGN KEY (category_id) REFERENCES public.categories (id) ON UPDATE NO ACTION ON DELETE NO ACTION,
    FOREIGN KEY (location_lat, location_lon) REFERENCES public.location (lat, lon) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS public.compilations_events
(
    compilation_id BIGINT NOT NULL,
    event_id       BIGINT NOT NULL,
    FOREIGN KEY (event_id) REFERENCES public.events (id) ON UPDATE NO ACTION ON DELETE NO ACTION,
    FOREIGN KEY (compilation_id) REFERENCES public.compilations (id) ON UPDATE NO ACTION ON DELETE NO ACTION
);
CREATE TABLE IF NOT EXISTS public.participation_request
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created      TIMESTAMP WITHOUT TIME ZONE,
    status       CHARACTER VARYING(255),
    event_id     BIGINT,
    requester_id BIGINT,
    CONSTRAINT pk_participation_request PRIMARY KEY (id),
    FOREIGN KEY (event_id) REFERENCES public.events (id) ON UPDATE NO ACTION ON DELETE NO ACTION,
    FOREIGN KEY (requester_id) REFERENCES public.users (id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_participation_request_event_requester ON public.participation_request (event_id, requester_id);

